sudo: false
language: cpp
addons:
  apt:
    packages:
      - valgrind
      - lcov
      - doxygen
      - graphviz
matrix:
  include:
    - os: linux
      compiler: gcc
      env: VALGRIND=true  ANALYSIS=true  COVERAGE=true  DOXYGEN=true
    - os: linux
      compiler: clang
      env: VALGRIND=true  ANALYSIS=false COVERAGE=false DOXYGEN=false
    - os: osx
      compiler: gcc
      env: VALGRIND=false ANALYSIS=false COVERAGE=false DOXYGEN=false
    - os: osx
      compiler: clang
      env: VALGRIND=false ANALYSIS=false COVERAGE=false DOXYGEN=false
script:
  - |
      if [ ! -z "$encrypted_e845a59f36e1_key" -a ! -z "$encrypted_e845a59f36e1_iv" ] && $COVERAGE ; then
        CXXFLAGS="-Wall -Wextra -Wpedantic -Werror -g -fprofile-arcs -ftest-coverage -O0" \
          CFLAGS="-Wall -Wextra -Wpedantic -Werror -g -fprofile-arcs -ftest-coverage -O0" \
         LDFLAGS="-lgcov --coverage" cmake .
      elif $VALGRIND ; then
        CXXFLAGS="-Wall -Wextra -Wpedantic -Werror -g" \
          CFLAGS="-Wall -Wextra -Wpedantic -Werror -g" cmake .
      else
        CXXFLAGS="-Wall -Wextra -Wpedantic -Werror" \
          CFLAGS="-Wall -Wextra -Wpedantic -Werror" cmake .
      fi
  - make -j 4
  - ./cdnstest
